In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the data
data = pd.read_csv("data_core.csv")
data

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,Sandy,Maize,37,0,0,Urea
1,29.00,52.00,45.00,Loamy,Sugarcane,12,0,36,DAP
2,34.00,65.00,62.00,Black,Cotton,7,9,30,14-35-14
3,32.00,62.00,34.00,Red,Tobacco,22,0,20,28-28
4,28.00,54.00,46.00,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [3]:
# copy the data
df = data.copy()
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,Sandy,Maize,37,0,0,Urea
1,29.00,52.00,45.00,Loamy,Sugarcane,12,0,36,DAP
2,34.00,65.00,62.00,Black,Cotton,7,9,30,14-35-14
3,32.00,62.00,34.00,Red,Tobacco,22,0,20,28-28
4,28.00,54.00,46.00,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [4]:
df.head(5) #first rows

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.0,52.0,38.0,Sandy,Maize,37,0,0,Urea
1,29.0,52.0,45.0,Loamy,Sugarcane,12,0,36,DAP
2,34.0,65.0,62.0,Black,Cotton,7,9,30,14-35-14
3,32.0,62.0,34.0,Red,Tobacco,22,0,20,28-28
4,28.0,54.0,46.0,Clayey,Paddy,35,0,0,Urea

In [5]:
df.tail(5) # last rows

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [6]:
df.drop_duplicates()

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,Sandy,Maize,37,0,0,Urea
1,29.00,52.00,45.00,Loamy,Sugarcane,12,0,36,DAP
2,34.00,65.00,62.00,Black,Cotton,7,9,30,14-35-14
3,32.00,62.00,34.00,Red,Tobacco,22,0,20,28-28
4,28.00,54.00,46.00,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [7]:
d1 = df.copy()
d1

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,Sandy,Maize,37,0,0,Urea
1,29.00,52.00,45.00,Loamy,Sugarcane,12,0,36,DAP
2,34.00,65.00,62.00,Black,Cotton,7,9,30,14-35-14
3,32.00,62.00,34.00,Red,Tobacco,22,0,20,28-28
4,28.00,54.00,46.00,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [8]:
d1 =d1.drop_duplicates()
d1

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,Sandy,Maize,37,0,0,Urea
1,29.00,52.00,45.00,Loamy,Sugarcane,12,0,36,DAP
2,34.00,65.00,62.00,Black,Cotton,7,9,30,14-35-14
3,32.00,62.00,34.00,Red,Tobacco,22,0,20,28-28
4,28.00,54.00,46.00,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [9]:
d1.info() #finding isnull

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temparature      8000 non-null   float64
 1   Humidity         8000 non-null   float64
 2   Moisture         8000 non-null   float64
 3   Soil Type        8000 non-null   object
 4   Crop Type        8000 non-null   object
 5   Nitrogen         8000 non-null   int64
 6   Potassium        8000 non-null   int64
 7   Phosphorous      8000 non-null   int64
 8   Fertilizer Name  8000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 562.6+ KB

In [10]:
d1.describe()

,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,30.338895,59.210731,43.580862,18.429125,3.916375,18.512500
std,4.478262,8.177366,12.596156,11.852406,5.494807,13.244113
min,20.000000,40.020000,20.000000,0.000000,0.000000,0.000000
25%,27.050000,53.277500,33.967500,9.000000,0.000000,8.000000
50%,30.240000,59.110000,42.250000,14.000000,1.000000,18.000000
75%,33.460000,65.082500,52.950000,26.000000,5.000000,30.000000
max,40.000000,80.000000,70.000000,46.000000,23.000000,46.000000

In [11]:
d1.isna() # find null values

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
7995,False,False,False,False,False,False,False,False,False
7996,False,False,False,False,False,False,False,False,False
7997,False,False,False,False,False,False,False,False,False
7998,False,False,False,False,False,False,False,False,False
7999,False,False,False,False,False,False,False,False,False

In [12]:
d1.isna().sum() #count null values for each column

Temparature        0
Humidity           0
Moisture           0
Soil Type          0
Crop Type          0
Nitrogen           0
Potassium          0
Phosphorous        0
Fertilizer Name    0
dtype: int64

 # Encoding

In [13]:
from sklearn.preprocessing import LabelEncoder
le_soil = LabelEncoder()
le_crop = LabelEncoder()
le_fert = LabelEncoder()

In [14]:
d1

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,Sandy,Maize,37,0,0,Urea
1,29.00,52.00,45.00,Loamy,Sugarcane,12,0,36,DAP
2,34.00,65.00,62.00,Black,Cotton,7,9,30,14-35-14
3,32.00,62.00,34.00,Red,Tobacco,22,0,20,28-28
4,28.00,54.00,46.00,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
7996,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
7997,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
7998,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
7999,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [15]:
d1["Soil Type"] = le_soil.fit_transform(d1["Soil Type"])
d1["Crop Type"] = le_soil.fit_transform(d1["Crop Type"])
d1["Fertilizer Name"] = le_soil.fit_transform(d1["Fertilizer Name"])
d1

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26.00,52.00,38.00,4,3,37,0,0,6
1,29.00,52.00,45.00,2,8,12,0,36,5
2,34.00,65.00,62.00,0,1,7,9,30,1
3,32.00,62.00,34.00,3,9,22,0,20,4
4,28.00,54.00,46.00,1,6,35,0,0,6
...,...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,5,10,14,10,6
7996,39.39,71.67,49.34,0,0,35,0,0,0
7997,35.79,67.64,45.04,3,0,41,0,0,6
7998,37.78,73.38,36.03,0,9,10,3,30,5
7999,31.38,48.73,62.27,2,4,11,2,33,4

In [16]:
print(le_soil.fit(df["Soil Type"]).classes_)

['Black' 'Clayey' 'Loamy' 'Red' 'Sandy']

In [17]:
print(le_crop.fit(df["Crop Type"]).classes_)

['Barley' 'Cotton' 'Ground Nuts' 'Maize' 'Millets' 'Oil seeds' 'Paddy'
 'Pulses' 'Sugarcane' 'Tobacco' 'Wheat']

# Input and Output For Model

In [18]:
x_crop = d1.drop(["Crop Type","Fertilizer Name"],axis=1)
x_crop

,Temparature,Humidity,Moisture,Soil Type,Nitrogen,Potassium,Phosphorous
0,26.00,52.00,38.00,4,37,0,0
1,29.00,52.00,45.00,2,12,0,36
2,34.00,65.00,62.00,0,7,9,30
3,32.00,62.00,34.00,3,22,0,20
4,28.00,54.00,46.00,1,35,0,0
...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,10,14,10
7996,39.39,71.67,49.34,0,35,0,0
7997,35.79,67.64,45.04,3,41,0,0
7998,37.78,73.38,36.03,0,10,3,30
7999,31.38,48.73,62.27,2,11,2,33

In [19]:
y_crop = d1["Crop Type"]
y_crop

0       3
1       8
2       1
3       9
4       6
       ..
7995    5
7996    0
7997    0
7998    9
7999    4
Name: Crop Type, Length: 8000, dtype: int64

In [20]:
data = pd.concat([x_crop,y_crop],axis=1)
data

,Temparature,Humidity,Moisture,Soil Type,Nitrogen,Potassium,Phosphorous,Crop Type
0,26.00,52.00,38.00,4,37,0,0,3
1,29.00,52.00,45.00,2,12,0,36,8
2,34.00,65.00,62.00,0,7,9,30,1
3,32.00,62.00,34.00,3,22,0,20,9
4,28.00,54.00,46.00,1,35,0,0,6
...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,10,14,10,5
7996,39.39,71.67,49.34,0,35,0,0,0
7997,35.79,67.64,45.04,3,41,0,0,0
7998,37.78,73.38,36.03,0,10,3,30,9
7999,31.38,48.73,62.27,2,11,2,33,4

# Train Crop Prediction Model

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
xc_train,xc_test,yc_train,yc_test = train_test_split(x_crop,y_crop,test_size=0.2,random_state=42)

In [23]:
from sklearn.ensemble import RandomForestClassifier
Rc = RandomForestClassifier

In [24]:
crop_model = RandomForestClassifier(n_estimators=100,random_state=42)

In [25]:
crop_model.fit(x_crop,y_crop)

RandomForestClassifier(random_state=42)

In [26]:
yc_pred=crop_model.predict(xc_test)

# Crop Model Accuracy

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
crop_acurracy=accuracy_score(yc_test,yc_pred)
print("crop prediction accuracy:",crop_acurracy* 100)

crop prediction accuracy: 100.0

In [29]:
x_fert=d1.drop('Fertilizer Name',axis=1)
x_fert

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,26.00,52.00,38.00,4,3,37,0,0
1,29.00,52.00,45.00,2,8,12,0,36
2,34.00,65.00,62.00,0,1,7,9,30
3,32.00,62.00,34.00,3,9,22,0,20
4,28.00,54.00,46.00,1,6,35,0,0
...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,5,10,14,10
7996,39.39,71.67,49.34,0,0,35,0,0
7997,35.79,67.64,45.04,3,0,41,0,0
7998,37.78,73.38,36.03,0,9,10,3,30
7999,31.38,48.73,62.27,2,4,11,2,33

In [30]:
y_fert=d1['Fertilizer Name']
y_fert

0       6
1       5
2       1
3       4
4       6
       ..
7995    6
7996    0
7997    6
7998    5
7999    4
Name: Fertilizer Name, Length: 8000, dtype: int64

In [31]:
xf_train,xf_test,yf_train,yf_test=train_test_split(x_fert,y_fert,test_size=0.2,random_state=42)

In [32]:
fert_model=RandomForestClassifier(n_estimators=100,random_state=42)

In [33]:
fert_model.fit(x_fert,y_fert)

RandomForestClassifier(random_state=42)

In [34]:
yf_pred=fert_model.predict(xf_test)

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
fer_acurracy=accuracy_score(yf_test,yf_pred)
print("crop prediction accuracy:",fer_acurracy* 100)

crop prediction accuracy: 100.0

In [37]:
import joblib
import pickle

In [38]:
pickle.dump(crop_model, open("crop_model.pkl", "wb"))
pickle.dump(fert_model, open("fertilizer_model.pkl", "wb"))